In [1]:
import numpy as np

In [11]:
def solve(a,b,c):
  a_np = np.array(a)
  b_np = np.array(b)
  c_np = np.array(c)
  print(f"Addition A+B:\n {a_np + b_np}")
  print(f"Subtraction B-A:\n {b_np - a_np}")
  print(f"Matrix Multiplication A*C:\n {a_np @ c_np}")
  print(f"Matrix Multiplication A*B*C:\n {a_np @ b_np @ c_np}")

In [12]:
a = [[1, 2, 4], [7, 5, -2], [-2, 1, 3]]
b = [[-1, 0, 3], [2, -6, 1], [-7, 1, 5]]
c = [[-2, 3], [4, 0], [7, -1]]
solve(a,b,c)

Addition A+B:
 [[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]
Subtraction B-A:
 [[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]
Matrix Multiplication A*C:
 [[34 -1]
 [-8 23]
 [29 -9]]
Matrix Multiplication A*B*C:
 [[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [13]:
a = [[0, 3, 4], [-7, 1, -2], [2, -1, 3]]
b = [[1, 2, 4], [7, 0, -2], [-3, -2, 5]]
c = [[-3, 2], [0, 4], [-1, 7]]
solve(a,b,c)

Addition A+B:
 [[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]
Subtraction B-A:
 [[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]
Matrix Multiplication A*C:
 [[ -4  40]
 [ 23 -24]
 [ -9  21]]
Matrix Multiplication A*B*C:
 [[ -41   84]
 [  22 -308]
 [  17  139]]


In [14]:
a = [[5, 2, 9], [7, 0, -2], [-2, 1, 6]]
b = [[1, -2, 1], [7, 5, -2], [-2, 8, 3]]
c = [[-2, 3], [4, 5], [0, -1]]
solve(a,b,c)

Addition A+B:
 [[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]
Subtraction B-A:
 [[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]
Matrix Multiplication A*C:
 [[ -2  16]
 [-14  23]
 [  8  -7]]
Matrix Multiplication A*B*C:
 [[ 286  335]
 [-142 -118]
 [ 242  250]]


In [15]:
a = [[1, -2, 8], [7, 5, -2], [-2, 3, 0]]
b = [[0, 2, 4], [1, -3, -2], [-2, 1, 3]]
c = [[0, 3], [5, -4], [7, -1]]
solve(a,b,c)

Addition A+B:
 [[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]
Subtraction B-A:
 [[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]
Matrix Multiplication A*C:
 [[ 46   3]
 [ 11   3]
 [ 15 -18]]
Matrix Multiplication A*B*C:
 [[ 304 -150]
 [  69   27]
 [-163   75]]


In [16]:
a = [[9, 2, 4], [7, 5, -5], [6, -2, 3]]
b = [[8, 2, 4], [0, 1, -3], [-2, 1, 6]]
c = [[-2, 0], [4, 8], [1, -1]]
solve(a,b,c)

Addition A+B:
 [[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]
Subtraction B-A:
 [[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]
Matrix Multiplication A*C:
 [[ -6  12]
 [  1  45]
 [-17 -19]]
Matrix Multiplication A*B*C:
 [[ 22 138]
 [-93 129]
 [ 16  56]]


In [18]:
def reverse(a):
  np_a = np.array(a)
  print(f"Original Matrix:\n {np_a}")
  print(f"Reversed Matrix:\n {np.linalg.inv(np_a)}")

In [19]:
a = [[1, -2, 8], [7, 5, -2], [-2, 3, 0]]
reverse(a)

Original Matrix:
 [[ 1 -2  8]
 [ 7  5 -2]
 [-2  3  0]]
Reversed Matrix:
 [[ 0.02439024  0.09756098 -0.14634146]
 [ 0.01626016  0.06504065  0.23577236]
 [ 0.12601626  0.00406504  0.07723577]]


In [20]:
a = [[5, 2, 9], [7, 0, -2], [-2, 1, 6]]
reverse(a)

Original Matrix:
 [[ 5  2  9]
 [ 7  0 -2]
 [-2  1  6]]
Reversed Matrix:
 [[ -0.66666667   1.           1.33333333]
 [ 12.66666667 -16.         -24.33333333]
 [ -2.33333333   3.           4.66666667]]


In [21]:
a = [[5, 2, 9], [7, 0, -2], [-2, 1, 6]]
reverse(a)

Original Matrix:
 [[ 5  2  9]
 [ 7  0 -2]
 [-2  1  6]]
Reversed Matrix:
 [[ -0.66666667   1.           1.33333333]
 [ 12.66666667 -16.         -24.33333333]
 [ -2.33333333   3.           4.66666667]]
